inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'
    - 'public/**/*'

# Layout
Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Lint
Lint/RedundantCopDisableDirective:
  Enabled: true

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

# Rails
Rails/FilePath:
  EnforcedStyle: arguments

Rails/TimeZone:
  EnforcedStyle: strict
